name: Basic Test Workflow

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  basic-test:
    name: Run basic checks
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Print hello
        run: echo "Workflow is running!"

      - name: List files
        run: ls -R .

  
  deploy_prod:
    name: Deploy to PROD
    runs-on: ubuntu-latest
    needs: basic-test
    steps:
      - name: Waiting for manual confirmation
        uses: trstringer/manual-approval@v1
        with:
          approvers: Zilic96
          minimum-approvals: 1
          issue-title: "Approve PROD deployment?"
          issue-body: "UAT succeeded. Approve PROD deployment."

      - name: Print hello
        run: echo "Workflow is running!"
